  unit-test:
    runs-on: ubuntu-latest
    needs: cppcheck  # Ensure cppcheck runs first
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies for GoogleTest
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ make

      - name: Clone and Build GoogleTest
        run: |
          git clone https://github.com/google/googletest.git
          mkdir build
          cd build
          cmake ../googletest
          make
          sudo make install

      - name: Build and Run Unit Tests
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug
          make
          ctest --output-on-failure
