# Pipeline 2: Static analysis and unit testing
name: Static Analysis and Testing Pipeline

on:
  workflow_run:
    workflows:
      - Build and Compile Pipeline
    types:
      - completed

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Install cppcheck
    - name: Install cppcheck
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck

    # Run Cppcheck for static analysis
    - name: Run static analysis with Cppcheck
      run: |
        cppcheck --enable=all --inconclusive --quiet \
          --suppress=missingIncludeSystem \
          --suppress=missingInclude .

  unit-tests:
    needs: static-analysis
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Install dependencies and GoogleTest
    - name: Install dependencies and GoogleTest
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential
        cd /tmp
        git clone https://github.com/google/googletest.git
        cd googletest
        cmake .
        sudo make install

    # Build the project and run unit tests
    - name: Build and run unit tests
      run: |
        mkdir build
        cd build
        cmake ..
        make
        ./runTests
