name: C++ Build and Compile Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Debug to check the file structure
    - name: List project files
      run: ls -R

    # Compile only if .cpp files are found
    - name: Compile C++ code
      run: |
        mkdir -p build
        cd build
        if ls ../*.cpp 1> /dev/null 2>&1; then
          g++ -Wall -Wextra -o program ../*.cpp
        else
          echo "No .cpp files found. Skipping compilation."
        fi
