name: Compile Code with GCC

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install g++
        run: sudo apt-get install -y g++

      - name: Compile Code with g++ and List Warnings
        run: |
          g++ -Wall -Wextra -o test_addition addition.cpp  # Use g++ instead of gcc
          if [ $? -ne 0 ]; then exit 1; fi  # Fail if compilation fails

      - name: Upload Compilation Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: compile-artifacts
          path: ./test_addition  # Adjust path for your compiled artifact
