name: C++ Build and Compile Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Compile only if .cpp files are found
    - name: Compile C++ code with GoogleTest
      run: |
        mkdir -p build
        cd build
        echo "Looking for .cpp files in ../"
        ls -l ../  # List files in the parent directory for debugging
        # Compile all the .cpp files explicitly listed
        cpp_files=$(ls ../*.cpp)
        if [ -z "$cpp_files" ]; then
          echo "No .cpp files found. Skipping compilation." > compile_output.log
        else
          echo "Compiling the following files: $cpp_files"
          g++ -Wall -Wextra -o program $cpp_files -lgtest -lgtest_main -pthread > compile_output.log 2>&1
        fi
        # Print the log in case of an error
        cat compile_output.log
        if [ $? -ne 0 ]; then
          echo "Compilation failed, exiting."
          exit 1
        fi

    # Upload compilation logs as artifacts
    - name: Upload compilation log
      uses: actions/upload-artifact@v3
      with:
        name: compilation-log
        path: build/compile_output.log
