name: Build and Compile Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Debug to check the file structure
    - name: List project files
      run: ls -R

    # Compile only if .c files are found
    - name: Compile code
      run: |
        mkdir -p build
        cd build
        if ls ../*.c 1> /dev/null 2>&1; then
          gcc -Wall -Wextra -o program ../*.c
        else
          echo "No .c files found. Skipping compilation."
