# Pipeline 1: Compile code and list warnings
name: Build and Compile Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Install GCC and dependencies
    - name: Install GCC and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++

    # Compile the code with warnings
    - name: Compile and list warnings
      run: |
        mkdir build
        cd build
        gcc -Wall -Wextra -o program ../src/*.c
